import { AppData } from './types';

export const CATEGORIES = [
  "All",
  "Browsers",
  "Security",
  "Multimedia",
  "Development",
  "Games",
  "Productivity",
  "Utilities",
  "Social"
];

export const MOCK_APPS: AppData[] = [
  // Existing Utility Apps
  {
    id: '1',
    name: 'Chrome Browser',
    developer: 'Google',
    category: 'Browsers',
    os: 'Windows',
    license: 'Free',
    version: '122.0.6261.94',
    downloads: '10B+',
    rating: 9.2,
    description: 'A fast, secure, and free web browser built for the modern web.',
  },
  {
    id: '2',
    name: 'VLC Media Player',
    developer: 'VideoLAN',
    category: 'Multimedia',
    os: 'Windows',
    license: 'Open Source',
    version: '3.0.20',
    downloads: '500M+',
    rating: 9.8,
    description: 'A free and open source cross-platform multimedia player and framework.',
  },
  {
    id: '3',
    name: 'Avast Free Antivirus',
    developer: 'Avast Software',
    category: 'Security',
    os: 'Windows',
    license: 'Free',
    version: '24.1',
    downloads: '400M+',
    rating: 8.5,
    description: 'Essential free antivirus protection that keeps your PC safe from malware.',
  },
  {
    id: '4',
    name: 'Visual Studio Code',
    developer: 'Microsoft',
    category: 'Development',
    os: 'Mac',
    license: 'Free',
    version: '1.87',
    downloads: '20M+',
    rating: 9.9,
    description: 'Code editing. Redefined. Free. Built on open source. Runs everywhere.',
  },
  {
    id: '5',
    name: 'Zoom Workplace',
    developer: 'Zoom Video Communications',
    category: 'Productivity',
    os: 'Android',
    license: 'Free',
    version: '5.17.11',
    downloads: '1B+',
    rating: 7.5,
    description: 'One platform to connect, create, and collaborate.',
  },
  {
    id: '6',
    name: 'Spotify',
    developer: 'Spotify AB',
    category: 'Multimedia',
    os: 'iOS',
    license: 'Free',
    version: '8.9.18',
    downloads: '1B+',
    rating: 9.0,
    description: 'Music for everyone. Millions of songs and podcasts. No credit card needed.',
  },
  {
    id: '7',
    name: '7-Zip',
    developer: 'Igor Pavlov',
    category: 'Utilities',
    os: 'Windows',
    license: 'Open Source',
    version: '23.01',
    downloads: '100M+',
    rating: 9.5,
    description: 'A file archiver with a high compression ratio.',
  },
  {
    id: '8',
    name: 'Discord',
    developer: 'Discord Inc.',
    category: 'Productivity',
    os: 'Windows',
    license: 'Free',
    version: '1.0.9030',
    downloads: '300M+',
    rating: 9.1,
    description: 'Your place to talk and hang out.',
  },
  {
    id: '9',
    name: 'Firefox',
    developer: 'Mozilla',
    category: 'Browsers',
    os: 'Mac',
    license: 'Open Source',
    version: '123.0',
    downloads: '200M+',
    rating: 9.3,
    description: 'Get the browser that protects what is important.',
  },

  // Games & New Requests
  {
    id: '10',
    name: 'Minecraft',
    developer: 'Mojang Studios',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: '1.20.4',
    downloads: '300M+',
    rating: 9.8,
    description: 'Prepare for an adventure of limitless possibilities as you build, mine, battle mobs, and explore the ever-changing Minecraft landscape.',
  },
  {
    id: '11',
    name: 'Grand Theft Auto V',
    developer: 'Rockstar Games',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: '1.68',
    downloads: '190M+',
    rating: 9.7,
    description: 'Experience the interwoven stories of three criminals in the sprawling city of Los Santos.',
  },
  {
    id: '12',
    name: 'Tetris',
    developer: 'The Tetris Company',
    category: 'Games',
    os: 'Windows',
    license: 'Free',
    version: 'Classic',
    downloads: '500M+',
    rating: 9.9,
    description: 'The world’s most popular puzzle game.',
  },
  {
    id: '13',
    name: 'Wii Sports',
    developer: 'Nintendo',
    category: 'Games',
    os: 'Windows', // Mapped for emulator/sim context
    license: 'Free',
    version: '1.0',
    downloads: '82M+',
    rating: 8.5,
    description: 'Legendary sports compilation. Tennis, Baseball, Bowling, Golf, and Boxing.',
  },
  {
    id: '14',
    name: 'PUBG: Battlegrounds',
    developer: 'KRAFTON',
    category: 'Games',
    os: 'Windows',
    license: 'Free',
    version: '28.1',
    downloads: '100M+',
    rating: 8.2,
    description: 'Land on strategic locations, loot weapons and supplies, and survive to become the last team standing.',
  },
  {
    id: '15',
    name: 'Mario Kart 8 Deluxe',
    developer: 'Nintendo',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: '3.0.1',
    downloads: '60M+',
    rating: 9.5,
    description: 'Hit the road with the definitive version of Mario Kart 8 and play anytime, anywhere.',
  },
  {
    id: '16',
    name: 'The Legend of Zelda: Breath of the Wild',
    developer: 'Nintendo',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: '1.6.0',
    downloads: '31M+',
    rating: 9.9,
    description: 'Step into a world of discovery, exploration, and adventure.',
  },
  {
    id: '17',
    name: 'Red Dead Redemption 2',
    developer: 'Rockstar Games',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: '1.32',
    downloads: '61M+',
    rating: 9.8,
    description: 'An epic tale of life in America’s unforgiving heartland.',
  },
  {
    id: '18',
    name: 'The Elder Scrolls V: Skyrim',
    developer: 'Bethesda Game Studios',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: 'Anniversary',
    downloads: '60M+',
    rating: 9.6,
    description: 'The next chapter in the highly anticipated Elder Scrolls saga.',
  },
  {
    id: '19',
    name: 'The Witcher 3: Wild Hunt',
    developer: 'CD Projekt Red',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: '4.04',
    downloads: '50M+',
    rating: 9.8,
    description: 'A story-driven, next-generation open world role-playing game.',
  },
  {
    id: '20',
    name: 'Super Mario Bros.',
    developer: 'Nintendo',
    category: 'Games',
    os: 'Web',
    license: 'Free',
    version: 'NES',
    downloads: '58M+',
    rating: 9.5,
    description: 'The classic game that defined a genre.',
  },
  {
    id: '21',
    name: 'The Last of Us Part I',
    developer: 'Naughty Dog',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: '1.1.2',
    downloads: '37M+',
    rating: 9.7,
    description: 'Endure and survive. Experience the emotional storytelling and unforgettable characters.',
  },
  {
    id: '22',
    name: 'Half-Life 2',
    developer: 'Valve',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: 'Update 2024',
    downloads: '12M+',
    rating: 9.7,
    description: 'The game that redefined the FPS genre with physics-based gameplay.',
  },
  {
    id: '23',
    name: 'Pac-Man',
    developer: 'Bandai Namco',
    category: 'Games',
    os: 'Web',
    license: 'Free',
    version: 'Anniversary',
    downloads: '100M+',
    rating: 9.0,
    description: 'Waka waka waka.',
  },
  {
    id: '24',
    name: 'Space Invaders',
    developer: 'Taito',
    category: 'Games',
    os: 'Web',
    license: 'Free',
    version: 'Classic',
    downloads: '50M+',
    rating: 8.8,
    description: 'Defend the earth from the alien invasion.',
  },
  {
    id: '25',
    name: 'The Legend of Zelda: Ocarina of Time',
    developer: 'Nintendo',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: 'N64',
    downloads: '7M+',
    rating: 9.9,
    description: 'Often cited as the greatest video game of all time.',
  },
  {
    id: '26',
    name: 'Doom',
    developer: 'id Software',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: '1993',
    downloads: '10M+',
    rating: 9.4,
    description: 'Rip and tear, until it is done.',
  },
  {
    id: '27',
    name: 'Street Fighter II',
    developer: 'Capcom',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: 'Turbo',
    downloads: '15M+',
    rating: 9.3,
    description: 'The fighting game that set the standard for the genre.',
  },
  {
    id: '28',
    name: 'World of Warcraft',
    developer: 'Blizzard Entertainment',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: 'Dragonflight',
    downloads: '100M+',
    rating: 9.0,
    description: 'Massively multiplayer online role-playing game.',
  },
  {
    id: '29',
    name: 'Final Fantasy VII',
    developer: 'Square Enix',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: 'Remake Intergrade',
    downloads: '14M+',
    rating: 9.6,
    description: 'A spectacular reimagining of one of the most visionary games ever.',
  },
  {
    id: '30',
    name: 'Mass Effect 2',
    developer: 'BioWare',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: 'Legendary',
    downloads: '5M+',
    rating: 9.8,
    description: 'Fight for the lost. Experience the second chapter of the Mass Effect trilogy.',
  },
  {
    id: '31',
    name: 'Portal 2',
    developer: 'Valve',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: 'Latest',
    downloads: '4M+',
    rating: 9.9,
    description: 'The perpetual testing initiative has been expanded.',
  },
  {
    id: '32',
    name: 'God of War',
    developer: 'Santa Monica Studio',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: '2018',
    downloads: '23M+',
    rating: 9.8,
    description: 'Kratos must master the rage that has driven him for many years.',
  },
  {
    id: '33',
    name: 'Baldur\'s Gate 3',
    developer: 'Larian Studios',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: 'Release',
    downloads: '10M+',
    rating: 9.9,
    description: 'Gather your party and return to the Forgotten Realms.',
  },
  {
    id: '34',
    name: 'Counter-Strike 2',
    developer: 'Valve',
    category: 'Games',
    os: 'Windows',
    license: 'Free',
    version: '2.0',
    downloads: '45M+',
    rating: 9.0,
    description: 'The next era of the world’s most popular shooter.',
  },
  {
    id: '35',
    name: 'Pokémon Red/Blue',
    developer: 'Game Freak',
    category: 'Games',
    os: 'Web',
    license: 'Free',
    version: 'GB',
    downloads: '30M+',
    rating: 9.5,
    description: 'Gotta catch em all!',
  },
  {
    id: '36',
    name: 'Super Mario 64',
    developer: 'Nintendo',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: 'N64',
    downloads: '11M+',
    rating: 9.7,
    description: 'Mario’s first foray into 3D platforming.',
  },
  {
    id: '37',
    name: 'Metal Gear Solid',
    developer: 'Konami',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: 'Master Collection',
    downloads: '6M+',
    rating: 9.6,
    description: 'Tactical Espionage Action.',
  },
  {
    id: '38',
    name: 'Resident Evil 4',
    developer: 'Capcom',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: 'Remake',
    downloads: '12M+',
    rating: 9.7,
    description: 'Survival is just the beginning.',
  },
  {
    id: '39',
    name: 'BioShock',
    developer: '2K Games',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: 'Remastered',
    downloads: '4M+',
    rating: 9.5,
    description: 'A shooter unlike any you have ever played.',
  },
  {
    id: '40',
    name: 'Dark Souls',
    developer: 'FromSoftware',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: 'Remastered',
    downloads: '10M+',
    rating: 9.4,
    description: 'Prepare to Die.',
  },
  {
    id: '41',
    name: 'Chrono Trigger',
    developer: 'Square Enix',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: 'PC',
    downloads: '2M+',
    rating: 9.8,
    description: 'The timeless RPG classic returns.',
  },
  {
    id: '42',
    name: 'GoldenEye 007',
    developer: 'Rare',
    category: 'Games',
    os: 'Windows',
    license: 'Free',
    version: 'N64',
    downloads: '8M+',
    rating: 9.2,
    description: 'You are Bond. James Bond.',
  },
  {
    id: '43',
    name: 'Minecraft: Play with Friends',
    developer: 'Mojang',
    category: 'Games',
    os: 'Android',
    license: 'Paid',
    version: 'Bedrock',
    downloads: '500M+',
    rating: 9.0,
    description: 'Explore infinite worlds and build everything from the simplest of homes to the grandest of castles.',
  },
  {
    id: '44',
    name: 'Wii Sports Resort',
    developer: 'Nintendo',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: '1.0',
    downloads: '33M+',
    rating: 8.8,
    description: 'Set off for a resort experience.',
  },
  {
    id: '45',
    name: 'Animal Crossing: New Horizons',
    developer: 'Nintendo',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: '2.0',
    downloads: '43M+',
    rating: 9.5,
    description: 'Escape to a deserted island and create your own paradise.',
  },
  {
    id: '46',
    name: 'Stardew Valley',
    developer: 'ConcernedApe',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: '1.6',
    downloads: '30M+',
    rating: 9.9,
    description: 'You have inherited your grandfather’s old farm plot.',
  },
  {
    id: '47',
    name: 'Call of Duty 4: Modern Warfare',
    developer: 'Infinity Ward',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: 'Remastered',
    downloads: '17M+',
    rating: 9.4,
    description: 'The action thriller of the year.',
  },
  {
    id: '48',
    name: 'Halo: Combat Evolved',
    developer: 'Bungie',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: 'MCC',
    downloads: '10M+',
    rating: 9.5,
    description: 'The game that changed console gaming forever.',
  },
  {
    id: '49',
    name: 'Diablo II: Resurrected',
    developer: 'Blizzard',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: '2.4',
    downloads: '5M+',
    rating: 9.3,
    description: 'The definitive remaster of Diablo II.',
  },
  {
    id: '50',
    name: 'Star Wars: KOTOR',
    developer: 'BioWare',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: '1.0',
    downloads: '3M+',
    rating: 9.6,
    description: 'It is four thousand years before the Galactic Empire.',
  },
  {
    id: '51',
    name: 'Left 4 Dead 2',
    developer: 'Valve',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: '2.2',
    downloads: '15M+',
    rating: 9.7,
    description: 'Set in the zombie apocalypse.',
  },
  {
    id: '52',
    name: 'Batman: Arkham City',
    developer: 'Rocksteady Studios',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: 'GOTY',
    downloads: '12M+',
    rating: 9.8,
    description: 'Become the Dark Knight.',
  },
  {
    id: '53',
    name: 'The Legend of Zelda: ALttP',
    developer: 'Nintendo',
    category: 'Games',
    os: 'Windows',
    license: 'Free',
    version: 'SNES',
    downloads: '4M+',
    rating: 9.8,
    description: 'A Link to the Past.',
  },
  {
    id: '54',
    name: 'Super Metroid',
    developer: 'Nintendo',
    category: 'Games',
    os: 'Windows',
    license: 'Free',
    version: 'SNES',
    downloads: '3M+',
    rating: 9.7,
    description: 'The galaxy is at peace... or is it?',
  },
  {
    id: '55',
    name: 'Shadow of the Colossus',
    developer: 'Team Ico',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: 'Remake',
    downloads: '5M+',
    rating: 9.6,
    description: 'To bring back a girl from the dead, you must defeat 16 colossi.',
  },
  {
    id: '56',
    name: 'Journey',
    developer: 'thatgamecompany',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: 'PC',
    downloads: '2M+',
    rating: 9.5,
    description: 'Explore the ancient, mysterious world of Journey.',
  },
  {
    id: '57',
    name: 'System Shock 2',
    developer: 'Irrational Games',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: 'Enhanced',
    downloads: '1M+',
    rating: 9.4,
    description: 'The cult classic sci-fi horror FPS RPG.',
  },
  {
    id: '58',
    name: 'Deus Ex',
    developer: 'Ion Storm',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: 'GOTY',
    downloads: '3M+',
    rating: 9.6,
    description: 'The year is 2052 and the world is a dangerous and chaotic place.',
  },
  {
    id: '59',
    name: 'Metroid Prime',
    developer: 'Retro Studios',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: 'Remastered',
    downloads: '3M+',
    rating: 9.7,
    description: 'Samus Aran’s First 3D Adventure.',
  },
  {
    id: '60',
    name: 'Silent Hill 2',
    developer: 'Konami',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: 'Remake',
    downloads: '2M+',
    rating: 9.5,
    description: 'In my restless dreams, I see that town.',
  },
  {
    id: '61',
    name: 'GTA: San Andreas',
    developer: 'Rockstar Games',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: 'Definitive',
    downloads: '27M+',
    rating: 9.8,
    description: 'Five years ago Carl Johnson escaped from the pressures of life in Los Santos.',
  },
  {
    id: '62',
    name: 'Hollow Knight',
    developer: 'Team Cherry',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: '1.5',
    downloads: '3M+',
    rating: 9.7,
    description: 'Forge your own path in Hollow Knight! An epic action adventure through a vast ruined kingdom.',
  },
  {
    id: '63',
    name: 'Persona 5 Royal',
    developer: 'Atlus',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: 'Royal',
    downloads: '5M+',
    rating: 9.8,
    description: 'Don the mask of Joker and join the Phantom Thieves of Hearts.',
  },
  {
    id: '64',
    name: 'Overwatch 2',
    developer: 'Blizzard',
    category: 'Games',
    os: 'Windows',
    license: 'Free',
    version: '2.0',
    downloads: '50M+',
    rating: 8.0,
    description: 'A free-to-play, always-on, team-based action game set in an optimistic future.',
  },
  {
    id: '65',
    name: 'Fortnite',
    developer: 'Epic Games',
    category: 'Games',
    os: 'Windows',
    license: 'Free',
    version: 'Chapter 5',
    downloads: '400M+',
    rating: 8.5,
    description: 'Create, play, and battle with friends for free in Fortnite.',
  },
  {
    id: '66',
    name: 'God of War Ragnarök',
    developer: 'Santa Monica Studio',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: 'PC',
    downloads: '15M+',
    rating: 9.8,
    description: 'Kratos and Atreus must journey to each of the Nine Realms in search of answers.',
  },
  {
    id: '67',
    name: 'Baldur\'s Gate II',
    developer: 'BioWare',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: 'Enhanced',
    downloads: '2M+',
    rating: 9.6,
    description: 'Kidnapped. Imprisoned. Tortured. The wizard Irenicus holds you captive.',
  },
  {
    id: '68',
    name: 'Portal',
    developer: 'Valve',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: '1.0',
    downloads: '10M+',
    rating: 9.8,
    description: 'A new kind of single player game.',
  },
  {
    id: '69',
    name: 'Inside',
    developer: 'Playdead',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: '1.0',
    downloads: '3M+',
    rating: 9.5,
    description: 'Hunted and alone, a boy finds himself drawn into the center of a dark project.',
  },
  {
    id: '70',
    name: 'Return of the Obra Dinn',
    developer: 'Lucas Pope',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: '1.0',
    downloads: '1M+',
    rating: 9.7,
    description: 'An insurance adventure with minimal color.',
  },
  {
    id: '71',
    name: 'The Sims 4',
    developer: 'Maxis',
    category: 'Games',
    os: 'Windows',
    license: 'Free',
    version: 'Latest',
    downloads: '70M+',
    rating: 8.8,
    description: 'Play with life and discover the possibilities.',
  },
  {
    id: '72',
    name: 'Dota 2',
    developer: 'Valve',
    category: 'Games',
    os: 'Windows',
    license: 'Free',
    version: 'Latest',
    downloads: '100M+',
    rating: 9.0,
    description: 'The most-played game on Steam.',
  },
  {
    id: '73',
    name: 'Call of Duty: Mobile',
    developer: 'Activision',
    category: 'Games',
    os: 'Android',
    license: 'Free',
    version: 'Latest',
    downloads: '500M+',
    rating: 9.0,
    description: 'Console quality HD gaming on your phone.',
  },
  {
    id: '74',
    name: 'Minecraft Pocket Edition',
    developer: 'Mojang',
    category: 'Games',
    os: 'Android',
    license: 'Paid',
    version: 'PE',
    downloads: '100M+',
    rating: 9.1,
    description: 'Minecraft on your mobile device.',
  },
  {
    id: '75',
    name: 'Subway Surfers',
    developer: 'SYBO',
    category: 'Games',
    os: 'Android',
    license: 'Free',
    version: 'Latest',
    downloads: '1B+',
    rating: 9.2,
    description: 'DASH as fast as you can!',
  },
  {
    id: '76',
    name: 'Candy Crush Saga',
    developer: 'King',
    category: 'Games',
    os: 'Android',
    license: 'Free',
    version: 'Latest',
    downloads: '1B+',
    rating: 9.1,
    description: 'Switch and match Candies in this tasty puzzle adventure.',
  },
  {
    id: '77',
    name: 'Free Fire',
    developer: 'Garena',
    category: 'Games',
    os: 'Android',
    license: 'Free',
    version: 'Max',
    downloads: '1B+',
    rating: 8.8,
    description: 'Survival Shooter Game.',
  },
  {
    id: '78',
    name: 'Roblox',
    developer: 'Roblox Corporation',
    category: 'Games',
    os: 'Android',
    license: 'Free',
    version: 'Latest',
    downloads: '500M+',
    rating: 8.9,
    description: 'The ultimate virtual universe.',
  },
  {
    id: '79',
    name: 'Pokémon GO',
    developer: 'Niantic',
    category: 'Games',
    os: 'Android',
    license: 'Free',
    version: 'Latest',
    downloads: '1B+',
    rating: 8.5,
    description: 'Join Trainers across the globe who are discovering Pokémon.',
  },
  {
    id: '80',
    name: 'Clash of Clans',
    developer: 'Supercell',
    category: 'Games',
    os: 'Android',
    license: 'Free',
    version: 'Latest',
    downloads: '500M+',
    rating: 9.3,
    description: 'Epic combat strategy game.',
  },
  {
    id: '81',
    name: '8 Ball Pool',
    developer: 'Miniclip',
    category: 'Games',
    os: 'Android',
    license: 'Free',
    version: 'Latest',
    downloads: '500M+',
    rating: 9.0,
    description: 'The World\'s #1 Pool game.',
  },
  {
    id: '82',
    name: 'Ludo King',
    developer: 'Gametion',
    category: 'Games',
    os: 'Android',
    license: 'Free',
    version: 'Latest',
    downloads: '500M+',
    rating: 8.8,
    description: 'The most played Ludo game.',
  },
  {
    id: '83',
    name: 'Temple Run 2',
    developer: 'Imangi Studios',
    category: 'Games',
    os: 'Android',
    license: 'Free',
    version: '2.0',
    downloads: '500M+',
    rating: 9.0,
    description: 'Navigate perilous cliffs, zip lines, mines and forests.',
  },
  {
    id: '84',
    name: 'Clash Royale',
    developer: 'Supercell',
    category: 'Games',
    os: 'Android',
    license: 'Free',
    version: 'Latest',
    downloads: '100M+',
    rating: 9.1,
    description: 'Enter the Arena! From the creators of Clash of Clans.',
  },
  {
    id: '85',
    name: 'Honor of Kings',
    developer: 'Tencent Games',
    category: 'Games',
    os: 'Android',
    license: 'Free',
    version: 'Global',
    downloads: '100M+',
    rating: 9.0,
    description: 'The world\'s most played mobile MOBA.',
  },
  {
    id: '86',
    name: 'Plants vs. Zombies',
    developer: 'PopCap',
    category: 'Games',
    os: 'Android',
    license: 'Free',
    version: 'Free',
    downloads: '100M+',
    rating: 9.4,
    description: 'Stem a zombie attack on your yard!',
  },
  {
    id: '87',
    name: 'Angry Birds 2',
    developer: 'Rovio',
    category: 'Games',
    os: 'Android',
    license: 'Free',
    version: '2.0',
    downloads: '100M+',
    rating: 9.1,
    description: 'The Angry Birds are back in the sequel to the biggest mobile game.',
  },
  {
    id: '88',
    name: 'Fruit Ninja',
    developer: 'Halfbrick',
    category: 'Games',
    os: 'Android',
    license: 'Free',
    version: 'Classic',
    downloads: '500M+',
    rating: 9.0,
    description: 'Slice fruit, don’t slice bombs.',
  },
  {
    id: '89',
    name: 'My Talking Tom',
    developer: 'Outfit7',
    category: 'Games',
    os: 'Android',
    license: 'Free',
    version: 'Latest',
    downloads: '500M+',
    rating: 8.9,
    description: 'Adopt your very own baby kitten.',
  },
  {
    id: '90',
    name: 'The Oregon Trail',
    developer: 'Gameloft',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: 'Remake',
    downloads: '500K+',
    rating: 9.0,
    description: 'The official successor to the global phenomenon.',
  },
  {
    id: '91',
    name: 'Pong',
    developer: 'Atari',
    category: 'Games',
    os: 'Web',
    license: 'Free',
    version: 'Classic',
    downloads: '1B+',
    rating: 8.0,
    description: 'The game that started it all.',
  },
  {
    id: '92',
    name: 'Grand Theft Auto III',
    developer: 'Rockstar Games',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: 'Definitive',
    downloads: '17M+',
    rating: 9.3,
    description: 'Welcome to Liberty City.',
  },
  {
    id: '93',
    name: 'Super Mario World',
    developer: 'Nintendo',
    category: 'Games',
    os: 'Windows',
    license: 'Free',
    version: 'SNES',
    downloads: '20M+',
    rating: 9.8,
    description: 'Mario\'s first adventure on the SNES.',
  },
  {
    id: '94',
    name: 'Super Mario Bros. 3',
    developer: 'Nintendo',
    category: 'Games',
    os: 'Windows',
    license: 'Free',
    version: 'NES',
    downloads: '18M+',
    rating: 9.7,
    description: 'One of the best selling games of all time.',
  },
  {
    id: '95',
    name: 'Sonic the Hedgehog',
    developer: 'SEGA',
    category: 'Games',
    os: 'Android',
    license: 'Free',
    version: 'Classic',
    downloads: '50M+',
    rating: 9.2,
    description: 'The classic Sonic game optimized for mobile.',
  },
  {
    id: '96',
    name: 'Donkey Kong',
    developer: 'Nintendo',
    category: 'Games',
    os: 'Web',
    license: 'Free',
    version: 'Arcade',
    downloads: '10M+',
    rating: 9.0,
    description: 'How high can you get?',
  },
  {
    id: '97',
    name: 'Baldur\'s Gate',
    developer: 'BioWare',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: 'Enhanced',
    downloads: '3M+',
    rating: 9.4,
    description: 'The dawn of the RPG renaissance.',
  },
  {
    id: '98',
    name: 'StarCraft',
    developer: 'Blizzard',
    category: 'Games',
    os: 'Windows',
    license: 'Free',
    version: 'Remastered',
    downloads: '20M+',
    rating: 9.5,
    description: 'The ultimate RTS game.',
  },
  {
    id: '99',
    name: 'Half-Life',
    developer: 'Valve',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: '25th Anniversary',
    downloads: '9M+',
    rating: 9.6,
    description: 'Run. Think. Shoot. Live.',
  },
  {
    id: '100',
    name: 'SimCity 2000',
    developer: 'Maxis',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: 'Special',
    downloads: '5M+',
    rating: 9.2,
    description: 'The ultimate city simulator.',
  },
  {
    id: '101',
    name: 'Uncharted 2: Among Thieves',
    developer: 'Naughty Dog',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: 'Collection',
    downloads: '10M+',
    rating: 9.7,
    description: 'Drake is back.',
  },
  {
    id: '102',
    name: 'Persona 5',
    developer: 'Atlus',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: 'Vanilla',
    downloads: '3M+',
    rating: 9.5,
    description: 'Life will change.',
  },
  {
    id: '103',
    name: 'Hades',
    developer: 'Supergiant Games',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: '1.0',
    downloads: '5M+',
    rating: 9.9,
    description: 'Defy the god of the dead.',
  },
  {
    id: '104',
    name: 'Elden Ring',
    developer: 'FromSoftware',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: 'GOTY',
    downloads: '20M+',
    rating: 9.8,
    description: 'Rise, Tarnished.',
  },
  {
    id: '105',
    name: 'Control',
    developer: 'Remedy',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: 'Ultimate',
    downloads: '3M+',
    rating: 9.2,
    description: 'A supernatural 3rd person action-adventure.',
  },
  {
    id: '106',
    name: 'Gears of War 2',
    developer: 'Epic Games',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: 'Xbox',
    downloads: '6M+',
    rating: 9.5,
    description: 'Bigger, better, and more badass.',
  },
  {
    id: '107',
    name: 'Fire Emblem: Three Houses',
    developer: 'Intelligent Systems',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: 'Switch',
    downloads: '4M+',
    rating: 9.3,
    description: 'War is coming to the continent of Fódlan.',
  },
  {
    id: '108',
    name: 'Tony Hawk\'s Pro Skater 2',
    developer: 'Neversoft',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: 'Remake',
    downloads: '10M+',
    rating: 9.8,
    description: 'Skateboarding greatness.',
  },
  {
    id: '109',
    name: 'Ms. Pac-Man',
    developer: 'Bandai Namco',
    category: 'Games',
    os: 'Web',
    license: 'Free',
    version: 'Arcade',
    downloads: '50M+',
    rating: 9.2,
    description: 'More mazes, more dots, more ghosts.',
  },
  {
    id: '110',
    name: 'The Walking Dead',
    developer: 'Telltale Games',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: 'Season 1',
    downloads: '8M+',
    rating: 9.6,
    description: 'A five-part game series set in the same universe as the award-winning comic series.',
  },
  {
    id: '111',
    name: 'Diablo III',
    developer: 'Blizzard',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: 'Eternal',
    downloads: '30M+',
    rating: 8.8,
    description: 'Evil is in its prime.',
  },
  {
    id: '112',
    name: 'Cyberpunk 2077',
    developer: 'CD Projekt Red',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: '2.1',
    downloads: '25M+',
    rating: 9.0,
    description: 'An open-world, action-adventure RPG set in the megalopolis of Night City.',
  },
  {
    id: '113',
    name: 'Monster Hunter: World',
    developer: 'Capcom',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: 'Iceborne',
    downloads: '23M+',
    rating: 9.5,
    description: 'Hunt or be hunted.',
  },
  {
    id: '114',
    name: 'Hogwarts Legacy',
    developer: 'Avalanche Software',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: 'Latest',
    downloads: '22M+',
    rating: 9.1,
    description: 'Live the unwritten. Your legacy is what you make of it.',
  },
  {
    id: '115',
    name: 'Payday 2',
    developer: 'Overkill Software',
    category: 'Games',
    os: 'Windows',
    license: 'Paid',
    version: 'Legacy',
    downloads: '40M+',
    rating: 9.0,
    description: 'Action-packed, four-player co-op shooter.',
  },
  {
    id: '116',
    name: 'Apex Legends',
    developer: 'Respawn',
    category: 'Games',
    os: 'Windows',
    license: 'Free',
    version: 'Season 20',
    downloads: '100M+',
    rating: 9.0,
    description: 'Master your Legend’s abilities and make strategic calls as you fight to be the last squad standing.',
  }
];
